In [8]:
import apyori

In [9]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [10]:
df = pd.read_excel('sampel.xlsx')
df.head()

,Bulan,KFTD,Lini,Produk,Target Sales,Realisasi Sales,Label
0,1,KFTD Jember,GENERIK,ACYCLOVIR,58360966.0,6700623.0,0
1,1,KFTD Jember,ETHICAL,ALBUMIN,0.0,122373760.0,1
2,1,KFTD Jember,ETHICAL,ALERGINE,201586000.0,14212000.0,0
3,1,KFTD Jember,GENERIK,ALLOPURINOL,33733440.0,1834560.0,0
4,1,KFTD Jember,GENERIK,ALPRAZOLAM,70654050.0,3636820.0,0

In [11]:
basket = (df          
.groupby(['Bulan', 'KFTD', 'Produk'])['Label']          
.sum().unstack().reset_index().fillna(0)           
.set_index(['Bulan','KFTD']))
basket

Produk                      ACYCLOVIR  ALBENDAZOLE  ALBUMIN  ALERGINE  \
Bulan KFTD
1     KFTD Jember                 0.0          0.0      1.0       0.0
      KFTD Kendari                0.0          0.0      1.0       0.0
      KFTD Kupang                 0.0          0.0      1.0       0.0
      KFTD Lampung                0.0          0.0      1.0       0.0
      KFTD Madiun                 0.0          0.0      1.0       0.0
...                               ...          ...      ...       ...
3     KFTD Tasikmalaya            0.0          0.0      1.0       0.0
      KFTD Tegal                  0.0          0.0      1.0       0.0
      KFTD Ternate                0.0          0.0      1.0       0.0
      KFTD UnitBisnisPusat        0.0          1.0      0.0       0.0
      KFTD Yogyakarta             0.0          0.0      1.0       0.0

Produk                      ALLOPURINOL  ALPRAZOLAM  AMBROXOL  AMOXYCILLIN  \
Bulan KFTD
1     KFTD Jember                   0.0         0.0       0.0          0.0
      KFTD Kendari                  0.0         0.0       0.0          0.0
      KFTD Kupang                   0.0         0.0       0.0          0.0
      KFTD Lampung                  0.0         0.0       0.0          0.0
      KFTD Madiun                   0.0         0.0       0.0          0.0
...                                 ...         ...       ...          ...
3     KFTD Tasikmalaya              0.0         1.0       0.0          0.0
      KFTD Tegal                    0.0         0.0       0.0          0.0
      KFTD Ternate                  0.0         0.0       0.0          0.0
      KFTD UnitBisnisPusat          0.0         0.0       0.0          0.0
      KFTD Yogyakarta               0.0         0.0       0.0          1.0

Produk                      AMPICILLIN  AMPLODIPINE  ...  VERAPAMIL  VERTIKAF  \
Bulan KFTD                                           ...
1     KFTD Jember                  1.0          0.0  ...        0.0       0.0
      KFTD Kendari                 1.0          0.0  ...        0.0       0.0
      KFTD Kupang                  0.0          0.0  ...        0.0       0.0
      KFTD Lampung                 0.0          0.0  ...        0.0       0.0
      KFTD Madiun                  0.0          0.0  ...        1.0       0.0
...                                ...          ...  ...        ...       ...
3     KFTD Tasikmalaya             1.0          0.0  ...        0.0       0.0
      KFTD Tegal                   0.0          0.0  ...        1.0       0.0
      KFTD Ternate                 1.0          0.0  ...        0.0       0.0
      KFTD UnitBisnisPusat         0.0          0.0  ...        0.0       0.0
      KFTD Yogyakarta              0.0          0.0  ...        1.0       0.0

Produk                      VIDISEP  VITAMIN B. COMPLEX  VITAMIN B1  \
Bulan KFTD
1     KFTD Jember               0.0                 0.0         0.0
      KFTD Kendari              0.0                 0.0         0.0
      KFTD Kupang               0.0                 0.0         0.0
      KFTD Lampung              0.0                 0.0         0.0
      KFTD Madiun               0.0                 0.0         0.0
...                             ...                 ...         ...
3     KFTD Tasikmalaya          0.0                 0.0         0.0
      KFTD Tegal                0.0                 0.0         0.0
      KFTD Ternate              0.0                 0.0         0.0
      KFTD UnitBisnisPusat      0.0                 0.0         0.0
      KFTD Yogyakarta           0.0                 0.0         0.0

Produk                      VITAMIN B12  VITAMIN C  VITAMINA  VIVITRA  \
Bulan KFTD
1     KFTD Jember                   0.0        0.0       0.0      0.0
      KFTD Kendari                  0.0        0.0       0.0      0.0
      KFTD Kupang                   0.0        0.0       0.0      0.0
      KFTD Lampung                  0.0        0.0       0.0      0.0
      KFTD Madiun                   0.0        0.0       0.0      0.0
...                                 ...        ...       ...      ...
3     KFTD Tasikmalaya              0.0        0.0       0.0      0.0
      KFTD Tegal                    0.0        0.0       0.0      0.0
      KFTD Ternate                  0.0        0.0       0.0      0.0
      KFTD UnitBisnisPusat          0.0        0.0       0.0      0.0
      KFTD Yogyakarta               0.0        0.0       0.0      0.0

Produk                      ZINK DISPERSIBEL
Bulan KFTD
1     KFTD Jember                        0.0
      KFTD Kendari                       0.0
      KFTD Kupang                        0.0
      KFTD Lampung                       0.0
      KFTD Madiun                        0.0
...                                      ...
3     KFTD Tasikmalaya                   0.0
      KFTD Tegal                         0.0
      KFTD Ternate                       0.0
      KFTD UnitBisnisPusat               0.0
      KFTD Yogyakarta                    0.0

[94 rows x 188 columns]

In [12]:
def encode_units(x):
    if x == 'no':
        return 0
    if x == 'yes':
        return 1
    else: 
        return 0
basket_sets = basket.applymap(encode_units)
basket_sets.head(100)

Produk                      ACYCLOVIR  ALBENDAZOLE  ALBUMIN  ALERGINE  \
Bulan KFTD
1     KFTD Jember                   0            0        0         0
      KFTD Kendari                  0            0        0         0
      KFTD Kupang                   0            0        0         0
      KFTD Lampung                  0            0        0         0
      KFTD Madiun                   0            0        0         0
...                               ...          ...      ...       ...
3     KFTD Tasikmalaya              0            0        0         0
      KFTD Tegal                    0            0        0         0
      KFTD Ternate                  0            0        0         0
      KFTD UnitBisnisPusat          0            0        0         0
      KFTD Yogyakarta               0            0        0         0

Produk                      ALLOPURINOL  ALPRAZOLAM  AMBROXOL  AMOXYCILLIN  \
Bulan KFTD
1     KFTD Jember                     0           0         0            0
      KFTD Kendari                    0           0         0            0
      KFTD Kupang                     0           0         0            0
      KFTD Lampung                    0           0         0            0
      KFTD Madiun                     0           0         0            0
...                                 ...         ...       ...          ...
3     KFTD Tasikmalaya                0           0         0            0
      KFTD Tegal                      0           0         0            0
      KFTD Ternate                    0           0         0            0
      KFTD UnitBisnisPusat            0           0         0            0
      KFTD Yogyakarta                 0           0         0            0

Produk                      AMPICILLIN  AMPLODIPINE  ...  VERAPAMIL  VERTIKAF  \
Bulan KFTD                                           ...
1     KFTD Jember                    0            0  ...          0         0
      KFTD Kendari                   0            0  ...          0         0
      KFTD Kupang                    0            0  ...          0         0
      KFTD Lampung                   0            0  ...          0         0
      KFTD Madiun                    0            0  ...          0         0
...                                ...          ...  ...        ...       ...
3     KFTD Tasikmalaya               0            0  ...          0         0
      KFTD Tegal                     0            0  ...          0         0
      KFTD Ternate                   0            0  ...          0         0
      KFTD UnitBisnisPusat           0            0  ...          0         0
      KFTD Yogyakarta                0            0  ...          0         0

Produk                      VIDISEP  VITAMIN B. COMPLEX  VITAMIN B1  \
Bulan KFTD
1     KFTD Jember                 0                   0           0
      KFTD Kendari                0                   0           0
      KFTD Kupang                 0                   0           0
      KFTD Lampung                0                   0           0
      KFTD Madiun                 0                   0           0
...                             ...                 ...         ...
3     KFTD Tasikmalaya            0                   0           0
      KFTD Tegal                  0                   0           0
      KFTD Ternate                0                   0           0
      KFTD UnitBisnisPusat        0                   0           0
      KFTD Yogyakarta             0                   0           0

Produk                      VITAMIN B12  VITAMIN C  VITAMINA  VIVITRA  \
Bulan KFTD
1     KFTD Jember                     0          0         0        0
      KFTD Kendari                    0          0         0        0
      KFTD Kupang                     0          0         0        0
      KFTD Lampung                    0          0         0        0
      KFTD Madiun                     0          0         0        0
...                                 ...        ...       ...      ...
3     KFTD Tasikmalaya                0          0         0        0
      KFTD Tegal                      0          0         0        0
      KFTD Ternate                    0          0         0        0
      KFTD UnitBisnisPusat            0          0         0        0
      KFTD Yogyakarta                 0          0         0        0

Produk                      ZINK DISPERSIBEL
Bulan KFTD
1     KFTD Jember                          0
      KFTD Kendari                         0
      KFTD Kupang                          0
      KFTD Lampung                         0
      KFTD Madiun                          0
...                                      ...
3     KFTD Tasikmalaya                     0
      KFTD Tegal                           0
      KFTD Ternate                         0
      KFTD UnitBisnisPusat                 0
      KFTD Yogyakarta                      0

[94 rows x 188 columns]

In [13]:
frequent_itemsets = apriori(basket_sets, min_support=0.7, use_colnames=True)

frequent_itemsets.head()

Empty DataFrame
Columns: [support, itemsets]
Index: []

In [7]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set

In [35]:
rules[ (rules['lift'] >= 1) &
       (rules['confidence'] >= 0.7) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(DUROGESIC),(ALBUMIN),0.893617,0.936170,0.861702,0.964286,1.030032,0.025124,1.787234
1,(ALBUMIN),(DUROGESIC),0.936170,0.893617,0.861702,0.920455,1.030032,0.025124,1.337386
2,(FENTANIL),(ALBUMIN),0.989362,0.936170,0.936170,0.946237,1.010753,0.009959,1.187234
3,(ALBUMIN),(FENTANIL),0.936170,0.989362,0.936170,1.000000,1.010753,0.009959,inf
4,(FENTANIL),(DUROGESIC),0.989362,0.893617,0.893617,0.903226,1.010753,0.009507,1.099291
5,(DUROGESIC),(FENTANIL),0.893617,0.989362,0.893617,1.000000,1.010753,0.009507,inf
6,(GLIBENCLAMIDE),(FENTANIL),0.702128,0.989362,0.702128,1.000000,1.010753,0.007469,inf
7,(FENTANIL),(GLIBENCLAMIDE),0.989362,0.702128,0.702128,0.709677,1.010753,0.007469,1.026005
8,(OMEPRAZOLE),(FENTANIL),0.734043,0.989362,0.734043,1.000000,1.010753,0.007809,inf
9,(FENTANIL),(OMEPRAZOLE),0.989362,0.734043,0.734043,0.741935,1.010753,0.007809,1.030585
10,"(DUROGESIC, FENTANIL)",(ALBUMIN),0.893617,0.936170,0.861702,0.964286,1.030032,0.025124,1.787234
11,"(FENTANIL, ALBUMIN)",(DUROGESIC),0.936170,0.893617,0.861702,0.920455,1.030032,0.025124,1.337386
12,"(DUROGESIC, ALBUMIN)",(FENTANIL),0.861702,0.989362,0.861702,1.000000,1.010753,0.009167,inf
13,(FENTANIL),"(DUROGESIC, ALBUMIN)",0.989362,0.861702,0.861702,0.870968,1.010753,0.009167,1.071809
14,(DUROGESIC),"(FENTANIL, ALBUMIN)",0.893617,0.936170,0.861702,0.964286,1.030032,0.025124,1.787234
15,(ALBUMIN),"(DUROGESIC, FENTANIL)",0.936170,0.893617,0.861702,0.920455,1.030032,0.025124,1.337386

In [36]:
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(DUROGESIC),(ALBUMIN),0.893617,0.936170,0.861702,0.964286,1.030032,0.025124,1.787234
1,(ALBUMIN),(DUROGESIC),0.936170,0.893617,0.861702,0.920455,1.030032,0.025124,1.337386
2,(FENTANIL),(ALBUMIN),0.989362,0.936170,0.936170,0.946237,1.010753,0.009959,1.187234
3,(ALBUMIN),(FENTANIL),0.936170,0.989362,0.936170,1.000000,1.010753,0.009959,inf
4,(FENTANIL),(DUROGESIC),0.989362,0.893617,0.893617,0.903226,1.010753,0.009507,1.099291

In [37]:
rules["Label"]="Yes"

In [38]:
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,Label
0,(DUROGESIC),(ALBUMIN),0.893617,0.936170,0.861702,0.964286,1.030032,0.025124,1.787234,Yes
1,(ALBUMIN),(DUROGESIC),0.936170,0.893617,0.861702,0.920455,1.030032,0.025124,1.337386,Yes
2,(FENTANIL),(ALBUMIN),0.989362,0.936170,0.936170,0.946237,1.010753,0.009959,1.187234,Yes
3,(ALBUMIN),(FENTANIL),0.936170,0.989362,0.936170,1.000000,1.010753,0.009959,inf,Yes
4,(FENTANIL),(DUROGESIC),0.989362,0.893617,0.893617,0.903226,1.010753,0.009507,1.099291,Yes

In [41]:
rules2=rules[["antecedents","consequents","Label"]]
rules2

              antecedents            consequents Label
0             (DUROGESIC)              (ALBUMIN)   Yes
1               (ALBUMIN)            (DUROGESIC)   Yes
2              (FENTANIL)              (ALBUMIN)   Yes
3               (ALBUMIN)             (FENTANIL)   Yes
4              (FENTANIL)            (DUROGESIC)   Yes
5             (DUROGESIC)             (FENTANIL)   Yes
6         (GLIBENCLAMIDE)             (FENTANIL)   Yes
7              (FENTANIL)        (GLIBENCLAMIDE)   Yes
8            (OMEPRAZOLE)             (FENTANIL)   Yes
9              (FENTANIL)           (OMEPRAZOLE)   Yes
10  (DUROGESIC, FENTANIL)              (ALBUMIN)   Yes
11    (FENTANIL, ALBUMIN)            (DUROGESIC)   Yes
12   (DUROGESIC, ALBUMIN)             (FENTANIL)   Yes
13             (FENTANIL)   (DUROGESIC, ALBUMIN)   Yes
14            (DUROGESIC)    (FENTANIL, ALBUMIN)   Yes
15              (ALBUMIN)  (DUROGESIC, FENTANIL)   Yes